#!/bin/sh
Green='\033[0;32m'
Red='\033[0;31m'
Color_Off='\033[0m'
White='\033[0;37m'
BWhite='\033[1;37m'

echo -e "${BWhite}::: pre-commit hook :::${Color_Off}"

echo -e "${White}Auto-formatting with Black...${Color_Off}"
black .

# Run Django tests
echo -e "${White}Running Django tests with coverage...${Color_Off}"

source env/bin/activate

coverage run --source="." manage.py test bsf

if [ $? -ne 0 ]; then
  echo -e "${Red}Commit aborted. Please fix your code first!${Color_Off}"
  exit 1
else
  echo -e "${Green}Tests passed, all good.${Color_Off}"
fi

echo -e "${White}Showing coverage report for bsf...${Color_Off}"

coverage report --include='bsf/*' --skip-covered -m --fail-under 85
if [ $? -ne 0 ]; then
  echo -e "${Red}Coverage is under reasonable 85%. Please write some tests next.${Color_Off}"
else
  echo -e "${Green}Great coverage!${Color_Off}"
fi

exit 0
