# Generated by Django 4.2 on 2023-04-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('rgb', models.CharField(max_length=6)),
                ('is_transparent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('brick_id', models.IntegerField(primary_key=True, serialize=False)),
                ('part_num', models.CharField(max_length=30)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf.color')),
            ],
        ),
    ]
