# Generated by Django 4.2 on 2023-04-12 14:41
#
# max_length=30 is too small for some color names

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bsf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
