# Generated by Django 4.2 on 2023-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bsf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='inventory_id',
            field=models.IntegerField(),
        ),
    ]
