# Generated by Django 4.2 on 2023-05-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brickincollectionquantity",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="brickinofferquantity",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="brickinsetquantity",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="brickinwishlistquantity",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="setincollectionquantity",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="setinofferquantity",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="setinwishlistquantity",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="OwnedLegoSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bsf.usercollection",
                    ),
                ),
                (
                    "realizes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bsf.legoset"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissingBrick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "brick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bsf.brick"
                    ),
                ),
                (
                    "overlays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bsf.brickinsetquantity",
                    ),
                ),
                (
                    "owned_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bsf.ownedlegoset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
