# Generated by Django 4.2 on 2023-06-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setincollectionquantity",
            name="in_use",
            field=models.IntegerField(default=0),
        ),
    ]
