# Generated by Django 4.2 on 2023-04-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0002_alter_legoset_inventory_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="brick",
            name="image_link",
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
