# Generated by Django 4.2 on 2023-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0002_customlegoset"),
    ]

    migrations.DeleteModel(
        name="CustomLegoSet",
    ),
