# Generated by Django 4.2 on 2023-04-12 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsf', '0002_alter_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrickInCollectionQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('brick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf.brick')),
            ],
        ),
        migrations.CreateModel(
            name='BrickInSetQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('brick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf.brick')),
            ],
        ),
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=256)),
                ('imageLink', models.CharField(max_length=256)),
                ('bricks', models.ManyToManyField(through='bsf.BrickInSetQuantity', to='bsf.brick')),
            ],
        ),
        migrations.CreateModel(
            name='SetInCollectionQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('brickset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf.legoset')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bricks', models.ManyToManyField(through='bsf.BrickInCollectionQuantity', to='bsf.brick')),
                ('sets', models.ManyToManyField(through='bsf.SetInCollectionQuantity', to='bsf.legoset')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='setincollectionquantity',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf.usercollection'),
        ),
        migrations.AddField(
            model_name='brickinsetquantity',
            name='brickset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf.legoset'),
        ),
        migrations.AddField(
            model_name='brickincollectionquantity',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf.usercollection'),
        ),
    ]
