# Generated by Django 4.2 on 2023-05-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0002_alter_brickincollectionquantity_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownedlegoset",
            name="missing_total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
