# Generated by Django 4.2 on 2023-04-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bsf", "0003_brick_image_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrickInWishlistQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("side", models.IntegerField(choices=[(0, "Offered"), (1, "Wanted")])),
                (
                    "brick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bsf.brick"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_bricks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrickInOfferQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("side", models.IntegerField(choices=[(0, "Offered"), (1, "Wanted")])),
                (
                    "brick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bsf.brick"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bsf.exchangeoffer",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="exchangeoffer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("offer_author", models.F("offer_receiver")), _negated=True
                ),
                name="check_author_receiver_different",
            ),
        ),
        migrations.AddConstraint(
            model_name="brickinwishlistquantity",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="check_quantity_positive_wishlist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brickinwishlistquantity",
            unique_together={("user", "brick")},
        ),
        migrations.AddConstraint(
            model_name="brickinofferquantity",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="check_quantity_positive_offer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brickinofferquantity",
            unique_together={("offer", "brick")},
        ),
    ]
