# Generated by Django 4.2 on 2023-05-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0003_legoset_video_link_delete_customlegoset"),
    ]

    operations = [
        migrations.AddField(
            model_name="legoset",
            name="custom_video_link",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
