# Generated by Django 4.2 on 2023-04-24 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bsf", "0003_brick_image_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrickStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.IntegerField()),
                ("min_recommended_age", models.IntegerField()),
                (
                    "brick_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bsf.legoset"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
