# Generated by Django 4.2 on 2023-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0003_ownedlegoset_missing_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brickincollectionquantity",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="brickinofferquantity",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="brickinsetquantity",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="brickinwishlistquantity",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="missingbrick",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="setincollectionquantity",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="setinofferquantity",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="setinwishlistquantity",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
