# Generated by Django 4.2 on 2023-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0004_brickstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="legoset",
            name="quantity_of_bricks",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legoset",
            name="theme",
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
