# Generated by Django 4.2 on 2023-05-22 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0004_rename_video_link_legoset_tutorial_video_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomLegoSet",
        ),
    ]
