# Generated by Django 4.2 on 2023-05-03 00:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bsf", "0004_exchangeoffer_setinwishlistquantity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="brickinofferquantity",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="setinofferquantity",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="brickinwishlistquantity",
            unique_together={("user", "brick", "side")},
        ),
        migrations.AlterUniqueTogether(
            name="setinwishlistquantity",
            unique_together={("user", "legoset", "side")},
        ),
    ]
