# Generated by Django 4.2 on 2023-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0005_delete_customlegoset"),
    ]

    operations = [
        migrations.AddField(
            model_name="brickstats",
            name="instruction_rating",
            field=models.IntegerField(
                choices=[(1, "Bad"), (2, "Medium"), (3, "Good")], default=2
            ),
            preserve_default=False,
        ),
    ]
