# Generated by Django 4.2 on 2023-04-30 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bsf", "0005_setinwishlistquantity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="setinwishlistquantity",
            unique_together={("user", "legoset", "side")},
        ),
    ]
