# Generated by Django 4.2 on 2023-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0006_brickstats_instruction_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="brickstats",
            name="review_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="brickstats",
            name="instruction_rating",
            field=models.IntegerField(),
        ),
    ]
