# Generated by Django 4.2 on 2023-05-01 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bsf", "0006_setinwishlistquantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetInOfferQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("side", models.IntegerField(choices=[(0, "Offered"), (1, "Wanted")])),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="brickinofferquantity",
            name="check_quantity_positive_offer",
        ),
        migrations.AlterUniqueTogether(
            name="setinwishlistquantity",
            unique_together={("user", "legoset")},
        ),
        migrations.AddConstraint(
            model_name="brickinofferquantity",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="check_quantity_positive_offer_brick",
            ),
        ),
        migrations.AddField(
            model_name="setinofferquantity",
            name="legoset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bsf.legoset"
            ),
        ),
        migrations.AddField(
            model_name="setinofferquantity",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bsf.exchangeoffer"
            ),
        ),
        migrations.AddConstraint(
            model_name="setinofferquantity",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="check_quantity_positive_offer_set",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="setinofferquantity",
            unique_together={("offer", "legoset")},
        ),
    ]
