# Generated by Django 4.2 on 2023-05-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bsf", "0007_brickstats_review_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legoset",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="legoset",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
