# Generated by Django 4.2 on 2023-05-31 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0004_alter_brickincollectionquantity_quantity_and_more"),
        ("bsf", "0008_legoset_author_legoset_visibility"),
    ]

    operations = []
