# Generated by Django 4.2 on 2023-06-01 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bsf", "0002_exchangeoffer_cash"),
        ("bsf", "0009_merge_20230531_1320"),
    ]

    operations = []
